### ISSUE TITLE
Frontend issues in Firefox

### ISSUE THREAD

**Issue by ApsOps** [matthewmueller/coderunner#18]
UI is not looking the way it should in Firefox 23.0.1 Works fine in chrome though.
One quick fix can be decreasing width of main or terminal div to 49%

**Comment by matthewmueller** [comment]
yikes, wtf firefox.

**Comment by ApsOps** [comment]
Is this not updated on http://coderunner.io/ ?

**Comment by rschmukler** [comment]
Doesn't look like it

**Comment by ApsOps** [comment]
@rschmukler Shouldn't it be `-moz-box-sizing` in place of `box-sizing` ?

**Comment by rschmukler** [comment]
@aps-sids the project is using [styl](http://github.com/visionmedia/styl) (see [here](https://github.com/MatthewMueller/coderunner/blob/master/lib/build/index.js#L7) ) which automatically includes vendor prefixes.
